data:
  secret:
    key: 2d861d47ab534b63bab3ed8181e9e09d

kakao:
  secret :
    kakaoClientId: "60ffdbd138489440034b2e2bb1f592e3"
    kakaoRedirectUri : "http://localhost:8080/api/members/getKakaoAccessToken"