#spring:
#  profiles:
#    include:
#      - secret
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

spring:
  profiles:
    include:
      - secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://concert-hall-ticket.cnaiu6sa65b5.ap-northeast-2.rds.amazonaws.com:3306/concert_hall_ticket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ldg1234!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: debug