spring:
  profiles:
    include:
      - secret
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
#      lettuce:
#        pool:
#          max-active:
#          max-idle:
#          min-idle:
#          max-wait:

data:
  secret:
    key: myKey